services:
    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        ports:
            - "8082:8082"
        volumes:
            - ./secrets:/run/secrets:ro
        networks:
            - test_net

secrets:
    GITHUB_TOKEN:
        external: true

networks:
    test_net:
        driver: bridge
        attachable: true
