services:
    pdfgen:
        # build: .
        # container_name: pdfgen
        labels:
            - "app=pdfgen"
        ports:
            - "8081:8081"
        image: pdfgen
        secrets:
            - GITHUB_TOKEN

secrets:
    GITHUB_TOKEN:
        external: true
